version: "3.7"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    restart: always

  dashboard:
    container_name: dashboard
    build: react-metrics-dashboard
    command: npm start
    volumes:
      - ./react-metrics-dashboard/src:/usr/src/app/src
    ports:
      - 3000:3000
  # twitter-go:
  #   build: twitter-go
  #   container_name: twitter-go
  #   volumes:
  #     - ./twitter-go:/app
  #   restart: on-failure
  #   depends_on:
  #     - redis
