global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: redis_exporter
    static_configs:
      - targets:
          [
            "redis_exporter:9121",
            "python_redis_exporter:5000",
            "node_exporter:9100",
          ]
